### ISSUE TITLE
Replace louietan/anki-editor with orgtre/anki-editor on MELPA

### ISSUE THREAD

**Issue by orgtre** [anki-editor/anki-editor#20]
So that everyone can download the most recent version easier.

I'm currently not in the clear about the procedure, but the necessary info seems to be collected here: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org

Worryingly it states: 

> Packages should be built from the official package repository. Forks of the official repository will not be accepted except in extreme circumstances.

but [pdf-tools](https://github.com/melpa/melpa/pull/7567) provides an example of how it can still be done if the original maintainer is unresponsive.

**Comment by slotThe** [comment]
Done in https://github.com/melpa/melpa/pull/9020
