### ISSUE TITLE
Unable to push notes

### ISSUE THREAD

**Issue by doolio** [anki-editor/anki-editor#33]
I'm seeing this error:

```
Wrong type argument: stringp, [org-element-deferred org-element--headline-parse-title (t) nil]
```

since updating to Org mode version 9.7-pre (release_9.6.7-662-gb89bc5 @ /home/doolio/projects/dotfiles/emacs/dot-emacs.d/straight/build/org/).

Backtrace as follows:

```
Debugger entered--Lisp error: (wrong-type-argument stringp [org-element-deferred org-element--headline-parse-title (t) nil])
  substring-no-properties([org-element-deferred org-element--headline-parse-title (t) nil])
  anki-editor--build-fields()
  anki-editor-note-at-point()
  anki-editor-push-note-at-point()
  funcall-interactively(anki-editor-push-note-at-point)
  call-interactively(anki-editor-push-note-at-point nil nil)
  command-execute(anki-editor-push-note-at-point)
```
Possible [related commit upstream](https://git.sr.ht/~bzg/org-mode/commit/bfe1179dcbcb2349979b3ac8fcc68a383521643b).

**Comment by Trotter-Wiz-Kiwanis** [comment]
I can confirm, it's not single case, happens also to me.

**Comment by doolio** [comment]
An odd observation in an effort to debug this issue....if you step through the function definition it works!

- Click on the `anki-editor--build-fields()` line in the backtrace buffer and enable `edebug` on this function with `C-u C-M-x`.
- Switch back to the backtrace buffer again and quit it with `q`.
- Switch back to the org headline I want to push to Anki and try to push it again...point then is inside the `anki-editor--build-fields()` function.
- Step through this function with `n`.
- When you finally step out of the function the note has been pushed to Anki!

I can then continue pushing notes successfully to Anki for the remainder of this Emacs session. The issue still exists on a new Emacs session. 

Not sure what we can conclude from that.

**Comment by ndvanforeest** [comment]
I have the same problem. The suggestion of doolio to step through the function works, although it would be nice if things would run without pressing the  n.

**Comment by doolio** [comment]
OK, so I or something deleted my `.git/refs/heads/master` file from my dotfiles repository which contains my `.emacs.d`. I had no choice but to delete my repository and re-clone from my remote `origin/master`. I lost some recent uncommitted changes but it was no big deal. 

Anyway, after I re-cloned my dotfiles repository and Emacs re-installed all my packages again this issue no longer occurs for me. I can't explain why. I have re-installed the same version of `org` and `anki-editor`. I presume some org related cache file within my `.emacs.d` had some issue in it that caused this issue with `anki-editor`. When I deleted my repo any such cache file was also deleted and such files are not committed so not present in my remote repository. I hope this helps someone suffering from the same issue.

**Comment by doolio** [comment]
[This comment ](https://github.com/radian-software/straight.el/issues/1107#issuecomment-1662711415) and the one that follows it seem to support what I discovered above.

**Comment by matiya** [comment]
So for me cleaning the .elc files and rebuilding the packages solved this issue.

In doom-emacs just run ./doom clean and ./doom build
