### ISSUE TITLE
Wrong number of arguments: #<subr request--curl-callback>, 2

### ISSUE THREAD

**Issue by e0fd96** [anki-editor/anki-editor#35]
I suddenly started getting this error when pushing notes.:
`
:ANKI_FAILURE_REASON: Wrong number of arguments: #<subr request--curl-callback>, 2`

The notes seem to appear in Anki, but the org properties drawer is not updated.

Using Debian 12 + Anki 2.1.66 + Org 9.5.5 + latest AnkiConnect

I assume related to: [https://github.com/louietan/anki-editor/issues/76](url)?

**Comment by slotThe** [comment]
@e0fd96 so, did the fix mentioned in the other issue work for you? I can't reproduce this at all

**Comment by e0fd96** [comment]
Thanks @slotThe ,
