### ISSUE TITLE
Notes without front nor back fields not pushed

### ISSUE THREAD

**Issue by whydnct** [anki-editor/anki-editor#38]
When trying to push notes with the syntax
```
* Heading
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: Default
:END:
Text
```
Emacs gets stuck in `Uploading notes in buffer file.org [###############################] 1/1 (100.00%)`

**Comment by Maddogskullcap** [comment]
I just submitted the same issue I must have missed yours. Mine will output `:ANKI_FAILURE_REASON: Missing fields` unless I have a *front/*back subheading.

**Comment by connormclaud** [comment]
I have the same issue.

**Comment by doolio** [comment]
@doctorguile Interested in submitting your changes here?

**Comment by connormclaud** [comment]
I performed extensive testing of the @doctorguile's fork and unfortunately it is buggy. It works incorrectly with lists, code blocks and sometimes omits back from the note. As a workaround I just put `* Back` between heading and subheading in all my notes and switched back to using this fork.
```
* Back
```
