### ISSUE TITLE
"Missing Fields" Failure Reason

### ISSUE THREAD

**Issue by Maddogskullcap** [anki-editor/anki-editor#43]
For context I use Doom emacs, but was unable to use the straight.el example and my package.el looks like the following code block. Additionaly, imported my anki cards using org-anki.
```
(package! anki-editor
   :recipe
  (:host github
   :repo "orgtre/anki-editor"))
```
When trying to run `anki-editor-push-notes` it outputs `:ANKI_FAILURE_REASON: Missing fields` I understand why because my card has no *front and *back subheading, but the documentation says I should be able to exclude them and anki-editor should understand that the heading is the front and the content of the heading is the back.

```
* Testcardface
:PROPERTIES:
:ANKI_DECK: CompTIA_A+_Core_1
:ANKI_NOTE_TYPE: Basic
:ANKI_FAILURE_REASON: Missing fields
:END:

Testcardback
```
I've tested with the front and back test headings and they import without issue. I've also had issues with subheadings inheriting the anki deck tags, and note type properties, wondering if the package did not install with the correct configuration, but that seems unlikely I'm newer to emacs so I'm probably just misunderstanding the syntax in the example.org.

Edit/Additional Info:
Org-anki imported all the fronts of my cards as headings, I am assuming it does the same for others so it's not great if I have to manually edit the few hundred cards I have to allow them to sync properly.

**Comment by slotThe** [comment]
Should be fixed by https://github.com/anki-editor/anki-editor/commit/be2fed0b47c992c9fe5ccb8cf9a72df9e47cdcd3 (and https://github.com/anki-editor/anki-editor/commit/c2d66f81382d0c0eb948f67c2cb8152e2b800f59)

**Comment by DevJac** [comment]
This appears to still be an issue. The follow note cannot be uploaded:

```
* How do you accept autosuggestions in the fish shell?
:PROPERTIES:
:ANKI_DECK: Default
:ANKI_NOTE_TYPE: Basic
:ANKI_FAILURE_REASON: Missing fields
:END:
Right arrow or ctrl-f. To accept a single word of the autosuggestion use alt.
```

Trying to push that note results in this message:

```
Pushed 1 notes, 1 of which are failed. Check property drawers for failure reasons. Once you’ve fixed the issues, you could use ‘anki-editor-retry-failure-notes’ to re-push the failed notes.
```
