### ISSUE TITLE
Cannot create a new note

### ISSUE THREAD

**Issue by yszhang95** [anki-editor/anki-editor#44]
I tried to use `M-x anki-editor-push-new-notes` with following content,
```
** 2024-04-19 16:11:53                                                          :LFUV:
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_DECK: CMS
:END:
*** Text
LFUV, {{c0::lepton flavor universality violation}}, implies {{c0::interactions with different couplings to electrons, muons, and tau leptons}} (disregarding {{c0::phase-space effects}}) that directly {{c0::distinguish among the charged leptons at the Lagrangian level}}.
*** Extra
```
I failed without knowing exactly reasons. I got in the properties section
```
:ANKI_FAILURE_REASON: cannot create note for unknown reason
```

From my side, it seems updating an existing note is possible. But creating a new one seems not.

**Comment by slotThe** [comment]
This is a horrible error message, but that's all we're getting from AnkiConnect, so no way around that. The issue is that you need to start with `c1`, and not `c0`.
