### ISSUE TITLE
Breaking changes in Org Element API in Org mode 9.7-pre

### ISSUE THREAD

**Issue by orgtre** [anki-editor/anki-editor#52]
Note that Org mode 9.7 is not released yet. For more info see the preliminary [release notes](https://github.com/bzg/org-mode/blob/9183e3c723b812360d1042196416d521db590e9f/etc/ORG-NEWS#L96).  

When running `anki-editor-push-notes` I get the following error for notes with at least one field subheading:  

> (wrong-type-argument stringp [org-element-deferred org-element&#x2013;headline-parse-title (t) nil])  

The backtrace leads to the first `substring-no-properties` in `anki-editor--build-fields`. Changing its argument to `(org-element-property :raw-value element nil t)`, i.e. making use of the new (in Org mode 9.7) force-undefer argument of org-element-property, seems to fix the issue.  

Furthermore, if the field subheading contains a latex element, I get this error:  

> (wrong-type-argument char-or-string-p [org-element-deferred org-element&#x2013;substring (0 8) nil])  

whose backtrace leads to `org-remove-indentation` in `anki-editor--ox-latex`. As before, changing its argument to `(org-element-property :value latex nil t)` seems to fix the issue.  

Retrieving note content before the first field subheading fails too, but without error. Changing `(org-element-at-point)` in `anki-editor--note-contents-before-subheading` to `(org-element-properties-resolve (org-element-at-point) 'force-undefer)`, seems to fix this.

There are probably further similar breakages. For backward compatibility the final fix might look something like [this](https://github.com/alphapapa/org-ql/commit/0e702ecb484673f8f8d85884f038fc0e84cb9bd3).

**Comment by orgtre** [comment]
Hm, it seems like in the now released 9.7 version these issues don't arise, so closing this without further investigation.

@slotThe I've had good success with https://gitlab.com/matsievskiysv/math-preview for getting latex fragments in Org mode to behave like I want, so it might be worth checking out.

**Comment by slotThe** [comment]
> @slotThe I've had good success with https://gitlab.com/matsievskiysv/math-preview for getting latex fragments in Org mode to behave like I want, so it might be worth checking out.

Thanks for the link! Though I have to say, Org's new latex preview system is probably the best I've ever used (in any editor, see e.g. [here](https://www.youtube.com/watch?v=n-AfvuV-bYo) for a showcase); one might say I'm quite happy with it :)

**Comment by augustfengd** [comment]
I think I experienced a similar issue with and I'm on org mode version 9.7.16. If I try to push a simple note like this,

```org
* Simple note
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: Tests
:END:
** Front
Simple note body
** Back
Lorem
```

I get this *:ANKI_FAILURE_REASON: Wrong type argument: integer-or-marker-p, nil* when I run `anki-editor-push-notes`.

The push succeeds when I delete the byte compiled code `anki-editor.elc` from the package. It doesn't seem to be an issue when I use a vanilla emacs 29 with the builtin org (9.6.15).
