### ISSUE TITLE
Working on Performance Improvements

### ISSUE THREAD

**Issue by jonprairie** [anki-editor/anki-editor#63]
I've been working on some performance improvements to anki-editor-push-notes; would the maintainers be interested in a pull request? The code is still rough (though I've been using it for a few days now) but in tests I can push 100+ new notes to anki in under four seconds. 

The improvements basically boil down to three things:
1. Successful updates to anki now hash note contents and save the hash in an org property on the note. Subsequent pushes hash the current contents and compare against the saved hash, only pushing to anki when a difference is found.
2. Pushes now defer exporting note fields until it's determined that the note will be sent to anki.
3. Pushes now batch up all api requests and send them as one call to anki at the end of processing. Some actions queue up further api calls upon successful completion, which are also all batched up for a second round of requests to the api, and so on until there are no more queued requests to process.

**Comment by slotThe** [comment]
> I've been working on some performance improvements to anki-editor-push-notes; would the maintainers be interested in a pull request? […]

Of course, performance improvements are always appreciated! The changes sound sensible enough; some (rough) benchmarks in the ensuing PR would be highly appreciated!

**Comment by jonprairie** [comment]
I created the pull request here: #64 
I tried not to alter too much outside of the push-notes function for the sake of stability. Let me know if there are any concerns you see, or style guidelines to conform to.
