### ISSUE TITLE
Allow missing field mapping order swap as an option

### ISSUE THREAD

**Issue by okomestudio** [anki-editor/anki-editor#65]
I propose the introduction of a flag for note types for which the field mapping order gets swapped, such that the sense of mapping heading content and the content before subheadings to the required note fields gets reversed.

The motivation goes as follows.

The current implementation of `anki-editor` allows fields to be omitted from the note structure according to the logic in [this post](https://github.com/eyeinsky/org-anki/issues/48#issuecomment-1216625730). This allows succinct, less verbose structure which is welcome.

For someone who makes excessive use of the “Cloze” note type, one minor improvement makes Anki notes be integrated into Org documents more seamlessly.

By default, we write a “Cloze” note as follows

```org
* This is heading
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
** Text

This is {{c1::text}}.
```

and the `anki-editor` maps

-   “This is {{c1::text}}.” as the content of “Text” field and
-   “This is heading” as the content of “Extra” field (due to the “Extra” field not explicitly supplied as a subheading).

Now, with the omission of the (mandatory) field, the abbreviated form looks like this:

```org
* This is heading
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:

This is {{c1::text}}.

```

As the main content of this “Cloze” note, interpreting “This is {{c1::text}}.” as the content of “Text” field would make sense, but the current logic actually does an unintuitive mapping:

-   “This is {{c1::text}}.” as the content of “Extra” field and
-   “This is heading” as the content of “Text” field.

This is so because the current implementation of the `anki-editor–map-fields` function simply maps the note heading to the first field (“Text” for “Cloze” note type) and the content before subheadings to the second field (“Extra” for “Cloze” note type).

This simple assignment makes sense for other note types like “Basic,” but not intuitive with “Cloze.”

A rather simple patch (a PR follows) allows an optional swapping of this field mapping order without breaking the existing behavior.

**Comment by slotThe** [comment]
Closed via #66
