### ISSUE TITLE
Help need to make it work with badlydrawnrob/anki

### ISSUE THREAD

**Issue by Aneeqasif** [anki-editor/anki-editor#69]
hy i have been using it for a couple of days and this plugin has drastically improved by ability to create cards. I stumbled upon [this work](https://github.com/badlydrawnrob/anki) and it feels like i am too close to having a perfect workflow if i can integrate anki-editor with these premade cards.
It may not be related to the context of this repo but i am kindly requesting help in general due to lack of expertise to do it myself. 

the issue is these cards work perfectly with   pandoc exported md->html [example](https://tinyurl.com/mr43ydea) but the highlighting don't work with orgmode exported html.  pleeeeeease help me!!

**Comment by slotThe** [comment]
For highlighting see `anki-editor-copy-styles`

**Comment by Aneeqasif** [comment]
> anki-editor-copy-styles

right , to make it simple i just need orgmode to use pandoc for converting src blocks is it possible?
