### ISSUE TITLE
Allow fields swap via property

### ISSUE THREAD

**Issue by okomestudio** [anki-editor/anki-editor#73]
To extend the usage of recently implemented [field swapping](https://github.com/anki-editor/anki-editor/issues/65) feature, I propose to allow overriding the value of custom variable `anki-editor-swap-two-fields` via Org properties.

The main benefit of the property `ANKI_SWAP_TWO_FIELDS` to set `anki-editor-swap-two-fields` is the higher granularity of control over which Anki notes to be influenced by this flag. For example, when you have a set of Anki notes of the following structure:

```org
* Zen
** What is Buddha?
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:

Three pounds of flax.

** Has a dog the Buddha nature?
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:

Mu.

* Vocab
:PROPERTIES:
:ANKI_SWAP_TWO_FIELDS: Basic
:END:
** Foo
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:

This word makes your code magically run 10x faster when used in tests.

** Bar
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:

A business selling alcoholic drinks.
```

By switching the swap behavior using the (inherited) property, we can more easily create the Anki notes with sensible QA structure:

-   Q: What is Buddha? A: Three pounds of flax.
-   Q: Has a dog the Buddha nature? A: Mu.
-   Q: This word makes your code magically run … A: Foo
-   Q: A business selling alcoholic drinks. A: Bar

The flexibility allows existing Org documents to adapt better to the Anki’s expected format.

The PR for the implementation follows.

**Comment by slotThe** [comment]
Closed by #74
