### ISSUE TITLE
Breaks with latest transient.el

### ISSUE THREAD

**Issue by agzam** [anki-editor/anki-editor#76]
I'm using latest transient.el and it looks like the package breaks with it.

Enabling anki-editor-mode throws:

<details>
  <summary>this error</summary>

       Debugger entered--Lisp error: (error "Need keyword, got 3")
         error("Need keyword, got %S" 3)
         transient--parse-suffix(anki-editor-ui ("a" " api check" anki-editor-api-check 3))
         transient--parse-child(anki-editor-ui ("a" " api check" anki-editor-api-check 3))
         #f(compiled-function (s) #<bytecode 0x112b7615d00ba2d7>)(("a" " api check" anki-editor-api-check 3))
         cl-mapcan(#f(compiled-function (s) #<bytecode 0x112b7615d00ba2d7>) (("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)))
         transient--parse-group(anki-editor-ui ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)])
         transient--parse-child(anki-editor-ui ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)])
         #f(compiled-function (s) #<bytecode 0x112b7615d00ba2d7>)(["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)])
         cl-mapcan(#f(compiled-function (s) #<bytecode 0x112b7615d00ba2d7>) (["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]))
         transient--parse-group(anki-editor-ui [["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]])
         transient--parse-child(anki-editor-ui [["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]])
         #f(compiled-function (s) #<bytecode -0x69e8181bc3b2b08>)([["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]])
         cl-mapcan(#f(compiled-function (s) #<bytecode -0x69e8181bc3b2b08>) ([["Org" ("i" " insert default note" anki-editor-insert-default-note :level 1) ("t" " set default note type" anki-editor-set-default-note-type :level 1) ("c" " cloze dwim" anki-editor-cloze-dwim :level 2)] ["" ("I" " insert note" anki-editor-insert-note :level 1) ("T" " set note type" anki-editor-set-note-type :level 1) ("d" " delete note" anki-editor-delete-note-at-point :level 1)]] [["Push" ("." " note at point        " anki-editor-push-note-at-point :level 2) ("n" " new notes            " anki-editor-push-new-notes :level 2) ("p" " push with ui" anki-editor-ui-push :level 1)] ["" ("b" " notes in buffer" anki-editor-push-notes :level 2) ("f" " failed notes" anki-editor-retry-failed-notes :level 2) ""]] [["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]] [["Misc" ("h" " subtree to html      " anki-editor-export-subtree-to-html :level 4) ("C" " copy styles          " anki-editor-copy-styles :level 4) ("F" " toggle format        " anki-editor-toggle-format :level 4)] ["" ("H" " region to html" anki-editor-convert-region-to-html :level 4) ("R" " remove styles" anki-editor-remove-styles :level 4) ("P" " toggle prepend heading" anki-editor-toggle-prepend-heading :level 4)]]))
         #f(compiled-function (arg1 arg2 &rest rest) "Define NAME as a transient prefix command.\n\nARGLIST are the arguments that command takes.\nDOCSTRING is the documentation string and is optional.\n\nThese arguments can optionally be followed by key-value pairs.\nEach key has to be a keyword symbol, either `:class' or a keyword\nargument supported by the constructor of that class.  The\n`transient-prefix' class is used if the class is not specified\nexplicitly.\n\nGROUPs add key bindings for infix and suffix commands and specify\nhow these bindings are presented in the popup buffer.  At least\none GROUP has to be specified.  See info node `(transient)Binding\nSuffix and Infix Commands'.\n\nThe BODY is optional.  If it is omitted, then ARGLIST is also\nignored and the function definition becomes:\n\n  (lambda ()\n    (interactive)\n    (transient-setup \\='NAME))\n\nIf BODY is specified, then it must begin with an `interactive'\nform that matches ARGLIST, and it must call `transient-setup'.\nIt may however call that function only when some condition is\nsatisfied; that is one of the reason why you might want to use\nan explicit BODY.\n\nAll transients have a (possibly nil) value, which is exported\nwhen suffix commands are called, so that they can consume that\nvalue.  For some transients it might be necessary to have a sort\nof secondary value, called a scope.  Such a scope would usually\nbe set in the commands `interactive' form and has to be passed\nto the setup function:\n\n  (transient-setup \\='NAME nil nil :scope SCOPE)" #<bytecode -0x4e7610d6ac2a614>)(anki-editor-ui nil "Transient for anki-editor." [["Org" ("i" " insert default note" anki-editor-insert-default-note :level 1) ("t" " set default note type" anki-editor-set-default-note-type :level 1) ("c" " cloze dwim" anki-editor-cloze-dwim :level 2)] ["" ("I" " insert note" anki-editor-insert-note :level 1) ("T" " set note type" anki-editor-set-note-type :level 1) ("d" " delete note" anki-editor-delete-note-at-point :level 1)]] [["Push" ("." " note at point        " anki-editor-push-note-at-point :level 2) ("n" " new notes            " anki-editor-push-new-notes :level 2) ("p" " push with ui" anki-editor-ui-push :level 1)] ["" ("b" " notes in buffer" anki-editor-push-notes :level 2) ("f" " failed notes" anki-editor-retry-failed-notes :level 2) ""]] [["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]] [["Misc" ("h" " subtree to html      " anki-editor-export-subtree-to-html :level 4) ("C" " copy styles          " anki-editor-copy-styles :level 4) ("F" " toggle format        " anki-editor-toggle-format :level 4)] ["" ("H" " region to html" anki-editor-convert-region-to-html :level 4) ("R" " remove styles" anki-editor-remove-styles :level 4) ("P" " toggle prepend heading" anki-editor-toggle-prepend-heading :level 4)]])
         macroexpand((transient-define-prefix anki-editor-ui nil "Transient for anki-editor." [["Org" ("i" " insert default note" anki-editor-insert-default-note :level 1) ("t" " set default note type" anki-editor-set-default-note-type :level 1) ("c" " cloze dwim" anki-editor-cloze-dwim :level 2)] ["" ("I" " insert note" anki-editor-insert-note :level 1) ("T" " set note type" anki-editor-set-note-type :level 1) ("d" " delete note" anki-editor-delete-note-at-point :level 1)]] [["Push" ("." " note at point        " anki-editor-push-note-at-point :level 2) ("n" " new notes            " anki-editor-push-new-notes :level 2) ("p" " push with ui" anki-editor-ui-push :level 1)] ["" ("b" " notes in buffer" anki-editor-push-notes :level 2) ("f" " failed notes" anki-editor-retry-failed-notes :level 2) ""]] [["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]] [["Misc" ("h" " subtree to html      " anki-editor-export-subtree-to-html :level 4) ("C" " copy styles          " anki-editor-copy-styles :level 4) ("F" " toggle format        " anki-editor-toggle-format :level 4)] ["" ("H" " region to html" anki-editor-convert-region-to-html :level 4) ("R" " remove styles" anki-editor-remove-styles :level 4) ("P" " toggle prepend heading" anki-editor-toggle-prepend-heading :level 4)]]))
         internal-macroexpand-for-load((transient-define-prefix anki-editor-ui nil "Transient for anki-editor." [["Org" ("i" " insert default note" anki-editor-insert-default-note :level 1) ("t" " set default note type" anki-editor-set-default-note-type :level 1) ("c" " cloze dwim" anki-editor-cloze-dwim :level 2)] ["" ("I" " insert note" anki-editor-insert-note :level 1) ("T" " set note type" anki-editor-set-note-type :level 1) ("d" " delete note" anki-editor-delete-note-at-point :level 1)]] [["Push" ("." " note at point        " anki-editor-push-note-at-point :level 2) ("n" " new notes            " anki-editor-push-new-notes :level 2) ("p" " push with ui" anki-editor-ui-push :level 1)] ["" ("b" " notes in buffer" anki-editor-push-notes :level 2) ("f" " failed notes" anki-editor-retry-failed-notes :level 2) ""]] [["Anki" ("g" " gui browse           " anki-editor-gui-browse :level 2) ("s" " sync AnkiWeb         " anki-editor-sync-collection :level 2)] ["" ("G" " gui add card" anki-editor-gui-add-cards :level 3) ("a" " api check" anki-editor-api-check 3)]] [["Misc" ("h" " subtree to html      " anki-editor-export-subtree-to-html :level 4) ("C" " copy styles          " anki-editor-copy-styles :level 4) ("F" " toggle format        " anki-editor-toggle-format :level 4)] ["" ("H" " region to html" anki-editor-convert-region-to-html :level 4) ("R" " remove styles" anki-editor-remove-styles :level 4) ("P" " toggle prepend heading" anki-editor-toggle-prepend-heading :level 4)]]) nil)
         load-with-code-conversion("/Users/ag/.emacs.d/.local/straight/build-30.0.92/anki-editor/anki-editor-ui.el" "/Users/ag/.emacs.d/.local/straight/build-30.0.92/anki-editor/anki-editor-ui.el" nil t)
         require(anki-editor-ui nil nil)
         #f(lambda () [t] (require 'anki-editor-ui nil nil))()
         eval-after-load-helper("/Users/ag/.emacs.d/.local/straight/build-30.0.92/anki-editor/anki-editor.elc")
         do-after-load-evaluation("/Users/ag/.emacs.d/.local/straight/build-30.0.92/anki-editor/anki-editor.elc")
         command-execute(anki-editor-mode record)
         #<subr execute-extended-command>(nil "anki-editor-mode" #("ank" 0 3 (ws-butler-chg chg)))
         ad-Advice-execute-extended-command(#<subr execute-extended-command> nil "anki-editor-mode" #("ank" 0 3 (ws-butler-chg chg)))
         apply(ad-Advice-execute-extended-command #<subr execute-extended-command> (nil "anki-editor-mode" #("ank" 0 3 (ws-butler-chg chg))))
         execute-extended-command(nil "anki-editor-mode" #("ank" 0 3 (ws-butler-chg chg)))
         funcall-interactively(execute-extended-command nil "anki-editor-mode" #("ank" 0 3 (ws-butler-chg chg)))
         command-execute(execute-extended-command)

</details>

**Comment by slotThe** [comment]
What version of transient are you using? Everything works correctly here with `0.7.9`

**Comment by agzam** [comment]
I'm using the latest transient.el - [35bbc3592903857c8f0696b4f85048769dc9ed8e](https://github.com/magit/transient/commit/35bbc3592903857c8f0696b4f85048769dc9ed8e), anki-editor.el fails even to eval, with `(error "Need keyword, got 3")`. 

I'm not sure what exactly has changed in Transient that makes the package incompatible, for users that are using pinned version perhaps it works as before, but it breaks with the latest stuff. Sorry, didn't mean to sound like complaining, more like a heads-up - the package may break with the next release of transient.el, just fyi.

**Comment by agzam** [comment]
It looks like new transient.el doesn't like the syntax of 

`(transient-define-prefix anki-editor-ui` - `:level x`, maybe the syntax of defining prefixes with levels has changed?

**Comment by agzam** [comment]
I have found the problem, see the PR.
